#!/bin/sh
echo "Content-type: text/html"
echo
echo "<html><header></header><body>"
echo "<h1>CPU information</h1>"
echo "Your embedded device uses the below processor:<pre><font color=Blue>"
echo `cat /proc/cpuinfo | grep Processor`
echo "</font></pre>"
echo "<p><a href=\"/\"><img src=\"/gohome.png\" border=\"0\"></a></p>"
echo "</body></html>"
