#!/bin/sh
sudo qemu-system-arm -m 32 -M versatilepb -kernel ../buildroot/data/zImage -append "root=/dev/nfs ip=172.20.0.2 nfsroot=172.20.0.1:$HOME/felabs-sysdev/appdev/qemu-rootfs/" -net nic -net tap,script=./qemu-ifup
