  #import "@local/bootlin:0.1.0": *

  #import "/typst/local/common.typ": *

  === TrustZone / Secure World

  - #link("https://developer.arm.com/documentation/100935/0100/The-TrustZone-hardware-architecture-?lang=en")[TrustZone]
    is an ARM-only hardware isolation mechanism

  - It is implemented on the
    #link("https://developer.arm.com/Architectures/A-Profile%20Architecture")[Application(A)-profiles]
    of ARMv7-9, this is what we discuss

  - Also implemented on the ARMv7-M (Microcontroller) profile, but
    differently

  - Splits the system into 2 #strong[worlds]: Secure and non-Secure

  - They are also called #strong[Trusted] / #strong[Rich] Execution
    Environment (TEE/REE)

  - This is #strong[orthogonal] to Exception Levels:

    - EL3 (Secure Monitor) only exists in #strong[Secure] world

    - EL2, if it exists, can exist in #strong[Secure],
      #strong[Non-Secure], or both

    - EL1 and EL0 must exist in #strong[both] security states

  === TrustZone / Secure World

  #align(center, [#image("Exception_Levels.pdf", width: 70%)])

  === World transitions: Secure to Non-Secure

  - The CPU starts executing at the highest EL: EL3, so in Secure World

  - It then sets up the rest of Secure World, then Normal World, in stages

  - Similar to the EL, the CPU keeps track of the security state in a
    register

    - SCR is the #emph[Secure Configuration Register (SCR)], bit 0 is the
      #emph[NS] bit

    - SCR can only be accessed in Secure EL1-3

    - Going from Secure World back to Non-Secure is simply setting
      #emph[NS] to 1

    - The Security model expects only the Secure Monitor to do this
      transition

  - The ARM spec leaves non-EL3 access to SCR as #emph[undefined]

  === World transitions: Back to Secure

  - The systems transitions from Non-Secure to Secure via exceptions,
    either:

    - asynchronous, via some #emph[FIQ] interrupts, depending on
      #emph[SCR.FIQ]

    - synchronous, generated by an #emph[smc] (#emph[secure monitor call])
      instruction

  - #emph[smc] cannot be called from EL0, so userland would first need to
    issue a #emph[svc]

  - The authority is the #emph[Secure Configuration Register (SCR)]'s NS
    bit

  - Accessing SCR from non-secure or from S-EL0 will fault.

  - Only the Secure Monitor (running at EL3) #strong[should] change it.

  === #link("https://www.trustedfirmware.org/")[Arm Trusted Firmware]

  - Trusted Firmware is an open-source reference Secure World
    implementation

  - It is the default Secure World for most ARM platforms

  - Comes in two flavours:

    - Trusted Firmware A (for the Application profile), or
      #link("https://www.trustedfirmware.org/projects/tf-a")[TF-A]

    - Trusted Firmware M (for the Microcontroler profile)
      #link("https://www.trustedfirmware.org/projects/tf-m")[TF-M]

  - There is now a Rust implementation of TF-A called Rusted Firmware A
    (#link("https://www.trustedfirmware.org/projects/rf-a")[RF-A])

  - Most importantly, TF-A implements the Secure Monitor

  - Uses a specific nomenclature to designate boot components

  === Trusted Firmware A (TF-A)

  - TF-A is split into 5 steps:

    - BootLoader 1, or BL1: the SoC vendor's ROM code

    - BootLoader 2, or BL2: "Trusted Boot firmware"

    - BootLoader 3-1, or
      #link("https://elixir.bootlin.com/arm-trusted-firmware/v2.14.0/source/bl31")[BL31]:
      EL3 Runtime

    - BootLoader 3-2, or
      #link("https://elixir.bootlin.com/arm-trusted-firmware/v2.14.0/source/bl32")[BL32]
      (optional): Secure-EL1 payload (Trusted OS, Trusted kernel, TEE)

    - BootLoader 3-3, or BL33: Non-trusted firmware, the "normal"
      bootloader

  - Only BL31 and BL32 are resident after boot is complete:

    - BL31 is responsible for routing Secure exceptions (and smcs) to the
      Secure World

    - BL32 handles some of these exceptions and smcs, potentially on
      behalf of TAs

  === ARMv8 boot sequence: TF-A names

  #align(center, [#image("/common/armv8-boot-sequence-generic.pdf", width: 60%)])

  === Trusted Firmware A (TF-A)

  - In a "standard" boot, where U-Boot is used as boot loader:

    - BL1: the vendor bootROM, non-resident

    - BL2: is implemented by the
      #link("https://docs.u-boot.org/en/latest/usage/spl_boot.html")[Second Program Loader]
      (SPL)

    - BL31: the runtime component of TF-A resident in EL3

    - BL32: OP-TEE

    - BL33: U-Boot proper

  === ARMv8 boot sequence

  #align(center, [#image("/common/armv8-boot-sequence-common-names.pdf", width: 60%)])

  === Rationale

  - The aim of TrustZone is to create a Trusted Execution Environment
    (TEE)

  - The isolation is backed by the hardware

  - Some hardware resources are only accessible to the TEE

  - Sounds familiar, why is it not simply the kernel?

    - attack surface: the TEE should be as small as possible

    - usage: can you ensure attackers do not get #emph[root]

    - virtualization: offer services securely to kernels you don't trust

  - The key concept is defense in depth

  === Trusted Execution Environments

  - The TEE is the part of Secure World that does things for the user

  - This is an A profile concept, the M profile equivalent is Secure
    Processing Environment (SPE)

  - There are different implementations of TEEs:

    - Trustsonic's
      #link("https://www.trustonic.com/secure-os/technology/")[Kinibi]

    - Samsung's #link("https://www.samsungknox.com/en")[Knox]

    - Qualcomm's
      #link("https://docs.qualcomm.com/doc/80-88500-4/topic/78_Qualcomm_TEE_5_0.html")[QTEE]

    - Huawei's iTrustee

  - Some are even Open Source:

    - Android's
      #link("https://source.android.com/docs/security/features/trusty")[Trusty],
      based on Little Kernel (LK)

    - Nvidia's Trusted Little Kernel (TLK), also based on LK: \
      `git://nv-tegra.nvidia.com/3rdparty/ote_partner/tlk.git`

    - OP-TEE, the reference Open Source TEE

  === Trusted Execution Environments

  - The TEE is an optional component

  - It does not normally offer service to Normal World directly

  - It does provide HW access to Trusted Applications

  - The TEE is the Secure World equivalent of the kernel, running in S-EL1

  - For further isolation, ARMv8 introduces Secure Partitions

    - Essentially run different instances of TEEs in isolated HW

    - A Secure Partition Manager runs at S-EL2 (SPMC) and (S-)EL3 (SPMD)

  - ARMv9 pushed this even further with the Realms extension

  === Trusted Applications

  - Trusted Applications are the secure world "userland"

  - OP-TEE has 2 main types of Trusted Apps:

    - Pseudo-TAs, statically compiled into the OP-TEE core binary

    - Usermode TAs are dynamically loaded by OP-TEE and run at S-EL0. 

  - Usermode TAs can be further subdivided into:

    - Early TAs: still stored in OP-TEE core, in a `data` section

    - REE FS TAs: loaded by the REE via `tee-supplicant`.

  - Because REE FS TAs are loaded from the REE, the TEE needs to
    authenticate them

    - OP-TEE expects REE FS TAs to be #link("TOBEFIXED.com")[signed]

    - the OP-TEE core embarks the public part of
      #text(size: 23pt)[#link("https://elixir.bootlin.com/op-tee/4.9.0/source/keys/default_ta.pem")[`default_ta.pem`]]

    - do #strong[NOT] ship OP-TEE with that key

  === Usecases

  - "Software HSM": this is why OP-TEE has a
    #link("https://github.com/OP-TEE/optee_os/tree/master/ta/pkcs11")[PKCS\#11 TA]

  - #link("https://github.com/OP-TEE/optee_ftpm")[fTPM]: OP-TEE

  - Payment processing

  - DRM

  - Biometrics (fingerprint unlock)

  - Hardware-isolated detection of non-secure malware

  === Issues

  - TrustZone is, ultimately, another security layer

  - The security guarantees it offers are only as strong as the
    implementation

  - Although it is hardware-backed, it is only useful if software is
    involved

  - Like all software, Secure World software can have bugs

    - #link("https://blog.thalium.re/posts/pivoting_to_the_secure_world/")[Arbitrary code execution in a Samsung TEE]

    - #link("https://www.keysight.com/blogs/en/authors/federico-menarini")[Other TEEGris vulnerabilities]

    - #link("https://blog.quarkslab.com/attacking-the-arms-trustzone.html")[S-EL0 stack buffer overflow in Qualcomm's TEE]

    - #link("https://blog.quarkslab.com/a-deep-dive-into-samsungs-trustzone-part-3.html")[EL3 execution via Samsung Kinibi]

  - Secure world configuration can be very HW-dependent
