#!/bin/sh

# Produces the lab archive that is published on
# http://free-electrons.com/labs/labs.tar.xz

ECHO=/bin/echo
GIT=/usr/bin/git
RM=/bin/rm
FIND=/usr/bin/find
TAR=/bin/tar
UNLZMA=/usr/bin/unxz
DIRNAME=/usr/bin/dirname
RSYNC=/usr/bin/rsync
SUDO=/usr/bin/sudo
CHOWN=/bin/chown

if [ ! -d lab-data ]; then
   $ECHO "ERROR: this script need to be run in the training-materials git repository"
   $ECHO "in the toplevel directory"
   exit 1
fi

if [ -z $1 ]; then
    $ECHO "ERROR: training name missing"
    exit 1
fi

if ! ls lab-data | grep -q $1; then
    $ECHO "ERROR: not a valid training name"
    exit 1
fi

FELABS=felabs-$1

# Updating repo

$ECHO "Git repository update..."
$GIT pull

# Copy lab data

$ECHO "Copying data from the git repository"
$RSYNC --exclude=.git -a --delete lab-data/$1/ $FELABS

# Uncompress compressed files

$ECHO "Extracting tar.xz archives (root permissions needed for device files)"

for f in `$FIND $FELABS -name "*.tar.xz"`; do
	$SUDO $TAR -C `dirname $f` -Jxf $f
	$RM $f
done

$SUDO $CHOWN -R $USER.$USER $FELABS

$ECHO "Uncompressing other .xz files"
$FIND $FELABS -name "*.xz" -exec $UNXZ {} ';'

# Create the final archive

$ECHO "Creating the final archive..."
$TAR Jcf ${FELABS}.tar.xz $FELABS

