BOOT_TIME_SLIDES = \
		first-slides \
		about-us \
		boot-time-thanks \
		boot-time-setup-and-download-sources \
		course-information-title \
		beagleboneblack-board \
		beaglecam \
		boot-time-shopping-list \
		course-information \
		board-setup-lab \
		boot-time-principles \
		build-system-bootloader-kernel-lab \
		boot-time-measuring \
		boot-time-toolchain \
		boot-time-c-libraries \
		boot-time-toolchain2 \
		boot-time-application \
		boot-time-init-scripts \
		boot-time-filesystems \
		boot-time-init-scripts2 \
		initramfs \
		boot-sequence-initramfs \
		boot-time-init-scripts3 \
		boot-time-kernel \
		boot-time-bootloader \
		boot-time-u-boot-falcon-mode \
		boot-time-hardware-init \
		boot-time-conclusions \
		boot-time-references \
		last-slides \

BOOT_TIME_BBB_LABS = boot-time-goals \
		     setup \
		     boot-time-sources-download \
		     boot-time-board-setup \
		     boot-time-build-system \
		     boot-time-build-bootloader \
		     boot-time-build-kernel-and-start-system \
		     boot-time-software-measurement \
		     boot-time-toolchain \
		     boot-time-application \
		     boot-time-init-scripts \
		     boot-time-filesystem-optimizations \
		     boot-time-kernel \
		     boot-time-bootloader \
