EMBEDDED_LINUX_SLIDES = \
		first-slides \
		about-us \
		course-information-title \
		xplained-board \
		sysdev-shopping-list \
		discovery-board-also-supported \
		qemu-also-supported \
		course-information \
		sysdev-intro \
		sysdev-dev-environment \
		setup-lab \
		sysdev-toolchains-title \
		sysdev-toolchains-definition \
		sysdev-toolchains-c-libraries-title \
		c-libraries \
		sysdev-toolchains-options \
		sysdev-toolchains-obtaining \
		sysdev-toolchains-lab \
		sysdev-bootloaders-title \
		sysdev-bootloaders-sequence \
		sysdev-bootloaders-u-boot \
		sysdev-bootloaders-lab \
		sysdev-linux-intro-title \
		sysdev-linux-intro-features \
		sysdev-linux-intro-versioning \
		sysdev-linux-intro-sources \
		sysdev-linux-tarballs-and-patches \
		sysdev-linux-intro-lab-sources \
		sysdev-kernel-building \
		sysdev-customizing-dt \
		sysdev-kernel-booting \
		sysdev-linux-intro-lab-cross-compilation \
		sysdev-linux-intro-modules \
		sysdev-root-filesystem-title \
		sysdev-root-filesystem-principles \
		initramfs \
		sysdev-root-filesystem-contents \
		sysdev-root-filesystem-device-files \
		sysdev-device-files \
		sysdev-root-filesystem-virtual-fs \
		sysdev-root-filesystem-minimal \
		boot-sequence-initramfs \
		sysdev-busybox \
		sysdev-block-filesystems \
		sysdev-flash-filesystems \
		sysdev-flash-filesystems-lab \
		sysdev-embedded-linux \
		sysdev-application-development \
		sysdev-realtime \
		sysdev-realtime-lab \
		sysdev-references \
		last-slides

EMBEDDED_LINUX_LABS   = setup \
		sysdev-toolchain \
		sysdev-u-boot \
		sysdev-kernel-fetch-and-patch \
		sysdev-kernel-cross-compiling \
		sysdev-tinysystem \
		sysdev-block-filesystems \
		sysdev-flash-filesystems \
		sysdev-thirdparty \
		sysdev-buildroot \
		sysdev-application-development \
		sysdev-application-debugging \
		sysdev-real-time
