EMBEDDED_LINUX_QEMU_SLIDES = \
		first-slides \
		about-us \
		course-information-title \
		qemu-board \
		discovery-board-also-supported \
		beagleboneblack-board-also-supported \
		beagleplay-board-also-supported \
		stm32mp2-board-also-supported \
		course-information \
		sysdev-intro \
		sysdev-dev-environment \
		setup-lab \
		sysdev-toolchains-title \
		sysdev-toolchains-definition \
		sysdev-toolchains-options \
		sysdev-toolchains-obtaining \
		sysdev-toolchains-lab \
		sysdev-bootloaders-title \
		sysdev-bootloaders-sequence \
		sysdev-bootloaders-u-boot \
		sysdev-bootloaders-tf-a \
		sysdev-bootloaders-lab \
		sysdev-linux-intro-title \
		sysdev-linux-intro-features \
		sysdev-linux-intro-versioning \
		sysdev-linux-intro-sources \
		sysdev-fetching-linux-kernel-sources-lab \
		sysdev-kernel-building \
		sysdev-customizing-dt \
		sysdev-kernel-booting \
		sysdev-linux-intro-lab-cross-compilation \
		sysdev-root-filesystem-title \
		sysdev-root-filesystem-principles \
		initramfs \
		sysdev-root-filesystem-contents \
		sysdev-root-filesystem-virtual-fs \
		sysdev-root-filesystem-minimal \
		boot-sequence-initramfs \
		sysdev-busybox \
		sysdev-hw-devices \
		sysdev-block-filesystems \
		sysdev-flash-filesystems \
		sysdev-cross-compiling-user-space \
		sysdev-build-systems \
		sysdev-licensing \
		sysdev-software-stacks \
		sysdev-application-development \
		sysdev-references \
		last-slides \
		sysdev-extra-slides

EMBEDDED_LINUX_QEMU_LABS   = \
                setup \
                sysdev-toolchain \
                sysdev-u-boot-qemu \
                sysdev-kernel-fetch-sources \
                sysdev-kernel-cross-compiling \
                sysdev-tinysystem \
                sysdev-accessing-hardware-qemu \
                sysdev-block-filesystems-qemu \
                sysdev-thirdparty-qemu \
                sysdev-buildroot-qemu \
		sysdev-application-development-qemu \
		sysdev-application-debugging-qemu \
