LINUX_KERNEL_SLIDES = \
		first-slides \
		about-us \
		course-information-title \
		beagleboneblack-board \
		kernel-shopping-list \
		course-information \
		setup-lab \
		kernel-introduction-title \
		sysdev-linux-intro-features \
		kernel-embedded-linux-usage-title \
		sysdev-linux-intro-sources \
		kernel-source-code-download-lab \
		kernel-source-code-title \
		kernel-source-code-drivers \
		kernel-source-code-layout \
		kernel-source-code-management \
		kernel-source-code-exploring-lab \
		sysdev-kernel-building \
		kernel-board-setup-kernel-compiling-and-booting-labs \
		sysdev-linux-intro-modules \
		kernel-driver-development-modules \
		kernel-driver-development-lab-modules \
		kernel-driver-development-general-apis \
		kernel-device-model \
		kernel-i2c \
		kernel-pinmuxing \
		kernel-frameworks \
		sysdev-device-files \
		kernel-frameworks2 \
		kernel-input \
		kernel-driver-development-memory \
		kernel-driver-development-io-memory \
		kernel-driver-development-lab-io-memory \
		kernel-misc-subsystem \
		kernel-driver-development-processes \
		kernel-driver-development-sleeping \
		kernel-driver-development-interrupts \
		kernel-driver-development-lab-interrupts \
		kernel-driver-development-concurrency \
		kernel-driver-development-lab-locking \
		kernel-driver-development-debugging \
		kernel-driver-development-lab-debugging \
		kernel-porting-title \
		kernel-porting-content \
		kernel-power-management-title \
		kernel-power-management-content \
		kernel-development-process-title \
		sysdev-linux-intro-versioning \
		kernel-contribution \
		kernel-resources-title \
		kernel-resources-references \
		last-slides \
		kernel-backup-slides-title \
		kernel-driver-development-dma \
		kernel-driver-development-mmap \

LINUX_KERNEL_LABS   = setup \
		kernel-sources-download \
		kernel-sources-exploring \
		kernel-board-setup \
		kernel-compiling-and-nfs-booting \
		kernel-module-simple \
		kernel-i2c-device-model \
		kernel-i2c-communication \
		kernel-i2c-input-interface \
		kernel-serial-iomem \
		kernel-serial-output \
		kernel-serial-interrupt \
		kernel-locking \
		kernel-debugging \
