LINUX_KERNEL_SLIDES = \
		first-slides \
		about-us \
		course-information-title \
		shopping-list-beaglebone \
		shopping-list-beagleplay \
		shopping-list-imx93-frdm \
		course-information \
		setup-lab \
		kernel-introduction-title \
		sysdev-linux-intro-features \
		kernel-intro-sources \
		kernel-source-code-download-lab \
		kernel-source-code-title \
		kernel-source-code-drivers \
		kernel-linux-usage-title \
		sysdev-kernel-building \
		sysdev-kernel-booting \
		kernel-board-setup-kernel-compiling-and-booting-labs \
		kernel-intro-modules \
		kernel-driver-development-modules \
		kernel-hw-devices \
		kernel-pinmuxing \
		kernel-device-model \
		kernel-i2c \
		kernel-frameworks \
		kernel-input \
		kernel-driver-development-memory \
		kernel-driver-development-io-memory \
		kernel-misc-subsystem \
		kernel-driver-development-processes \
		kernel-driver-development-sleeping \
		kernel-driver-development-interrupts \
		kernel-driver-development-concurrency \
		kernel-driver-development-dma \
		kernel-driver-development-debugging \
		kernel-porting \
		kernel-power-management \
		kernel-resources-references \
		last-slides \
		kernel-backup-slides-title \
		kernel-driver-development-mmap \
		kernel-driver-development-general-apis

LINUX_KERNEL_BBB_LABS = \
		setup \
		kernel-sources-download \
		kernel-sources-exploring \
		kernel-board-setup-bbb \
		kernel-compiling-and-nfs-booting-bbb \
		kernel-module-simple \
		kernel-i2c-describing-hardware-bbb \
		kernel-i2c-multiplexing-bbb \
		kernel-i2c-communication \
		kernel-i2c-input-interface \
		kernel-serial-iomem-bbb \
		kernel-serial-output \
		kernel-serial-interrupt \
		kernel-locking \
		kernel-serial-dma \
		kernel-debugging \

LINUX_KERNEL_BEAGLEPLAY_LABS = \
		setup \
		kernel-sources-download \
		kernel-sources-exploring \
		kernel-board-setup-beagleplay \
		kernel-compiling-and-nfs-booting-beagleplay \
		kernel-module-simple \
		kernel-i2c-describing-hardware-beagleplay \
		kernel-i2c-multiplexing-beagleplay \
		kernel-i2c-communication \
		kernel-i2c-input-interface \
		kernel-serial-iomem-beagleplay \
		kernel-serial-output \
		kernel-serial-interrupt \
		kernel-locking \
		kernel-serial-dma \
		kernel-debugging \

LINUX_KERNEL_IMX93_FRDM_LABS = \
		setup \
		kernel-sources-download \
		kernel-sources-exploring \
		kernel-board-setup-imx93-frdm \
		kernel-compiling-and-nfs-booting-imx93-frdm \
		kernel-module-simple \
		kernel-i2c-describing-hardware-imx93-frdm \
		kernel-i2c-multiplexing-imx93-frdm \
		kernel-i2c-communication \
		kernel-i2c-input-interface \
		kernel-serial-iomem-imx93-frdm \
		kernel-serial-output \
		kernel-serial-interrupt \
		kernel-locking \
		kernel-serial-dma \
		kernel-debugging \
