include conf/distro/kiss.conf

DISTRO_NAME = "security training Linux"
DISTRO_VERSION = "1.0"

SDK_VENDOR = "-securitytraining"
SDK_VERSION = "${DISTRO_VERSION}"

DISTRO_FEATURES = "ipv4 ipv6 wifi zeroconf usbgadget usbhost systemd pni-names seccomp acl xattr pam selinux rauc"
INIT_MANAGER = "systemd"

PREFERRED_PROVIDER_virtual/refpolicy ?= "refpolicy-standard"
FIRST_BOOT_RELABEL = "1"

# This should ideally live in machine/freiheit93.conf
KERNEL_IMAGETYPE = "fitImage"
FIT_KERNEL_COMP_ALG = "none"
FIT_KERNEL_COMP_EXTENSION = ""
IMAGE_BOOT_FILES = " ${KERNEL_IMAGETYPE}"
UBOOT_ARCH = "arm64"
# We need these to avoid the FIT image embedding a load address
# that will trigger an exception.
UBOOT_LOADADDRESS = "0x80400000"
UBOOT_ENTRYPOINT = "0x83000000"
