#!/bin/sh
if ! [ -e /dev/video0 ]
then
   echo "Waiting for /dev/video0 to be ready..."
   while ! [ -e /dev/video0 ]
   do
       sleep 0.001
   done
fi
echo "Starting ffmpeg"
ffmpeg -t 10 -f video4linux2 -video_size 544x288 -input_format mjpeg -i /dev/video0 -pix_fmt rgb565le -f fbdev /dev/fb0
/bin/sh
