#!/bin/sh
case "$1" in
        start|"")
		ffmpeg -t 10 -f video4linux2 -video_size 544x288 -input_format mjpeg -i /dev/video0 -pix_fmt rgb565le -f fbdev /dev/fb0
                ;;
        stop)
		killall ffmpeg
                ;;
        *)
                echo "Usage: playvideo {start|stop}" >&2
                exit 1
                ;;
esac
