#!/bin/sh
echo "Content-type: text/html"
echo
echo "<html><header></header><body>"
echo "<h1>CPU information</h1>"
echo "Here is information about the CPU in your embedded system:<pre><font color=Blue>"
cat /proc/cpuinfo
echo "</font></pre>"
echo "<p><a href=\"/index.html\"><img src=\"/gohome.png\" border=\"0\"></a></p>"
echo "</body></html>"
