#!/bin/sh
# Downloads all the Debian packages
# needed for our training labs
# Caution: very partial, news updating!

# Lab setup
apt install vim-full emacs nedit lzma

# Linux/Lab1
apt install patch cscope cbrowser ketchup

# Linux/Lab2
apt install qemu libqt3-mt-dev g++ libncurses-dev libglade2-dev

# Linux/Lab4
apt install nfs-kernel-server

# Linux/debugging (lab 6)
apt install gdb libftdi-dev

# Linux/PCI
apt install pciutils

# Sysdev / buildroot
apt install bison flex gettext texinfo
