#!/bin/sh
# Downloads all the Debian packages
# needed for our training labs
# Caution: very partial, news updating!

# Lab setup
apt-get install vim-full emacs nedit lzma

# Linux/Lab1
apt-get install patch cscope cbrowser ketchup

# Linux/Lab2
apt-get install qemu libqt3-mt-dev g++ libncurses-dev libglade2-dev

# Linux/Lab4
apt-get install nfs-kernel-server

# Linux/debugging (lab 6)
apt-get install gdb libftdi-dev

# Linux/PCI
apt-get install pciutils

# Sysdev / buildroot
apt-get install bison flex gettext texinfo
