# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-security-training"
BBFILE_PATTERN_meta-security-training = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-security-training = "10"

LAYERDEPENDS_meta-security-training = "core meta-kiss"
LAYERSERIES_COMPAT_meta-security-training = "scarthgap"
