#!/bin/sh
# Packages to install for the boot time workshop

sudo apt-get install picocom libxss1 git libncurses5-dev libqt4-dev u-boot-tools g++ bison flex gettext texinfo lzop ant openjdk-6-jdk meld inkscape
