[package]
name = "bootlin"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Bootlin <https://bootlin.com>"]
license = "MIT"
description = "Bootlin template for external communication"
categories = ["office"]
