#import "@local/bootlin:0.1.0": *

#import "/typst/local/common.typ": *

#show: bootlin-theme

#show raw.where(lang: "console", block: true): set text(size: 14pt)

#show raw.where(lang: "python", block: true): set text(size: 12pt)

= Application Debugging

== Good practices
<good-practices>

=== Good practices

- Some good practices can allow you to save time before even needing to
  use a debugger

- Compiler are now smart enough to detect a wide range of errors at
  compile-time using warnings

  - Using `-Werror -Wall -Wextra` is recommended if possible to catch
    errors as early as possible

- Compilers now offer static analysis capabilities

  - GCC allows to do so using the
    #link(
      "https://gcc.gnu.org/onlinedocs/gcc-11.1.0/gcc/Static-Analyzer-Options.html",
    )[-fanalyzer]
    flag

  - LLVM provides
    #link(
      "https://clang.llvm.org/docs/analyzer/user-docs/CommandLineUsage.html",
    )[dedicated tools]
    that can be used in build process

- You can also enable component-specific helpers/hardening

  - If you are using the GNU C library, you can for example enable
    #link(
      "https://www.gnu.org/software/libc/manual/html_node/Source-Fortification.html",
    )[_\_FORTIFY_SOURCE_]
    macro to add runtime checks on inputs (e.g: buffers)

== Building with debug information
<building-with-debug-information>

=== Debugging with ELF files

#table(
  columns: (75%, 25%),
  stroke: none,
  gutter: 15pt,
  [

    - GDB uses ELF files since they contain the debugging information

    - Debugging information uses the DWARF format

    - Allows the debugger to match addresses and symbol names, call sites,
      etc

    - Debugging information is generated by the compiler and included in the
      ELF file when compiled with `-g`

      - `-g1`: minimal debug information (enough for backtraces)

      - `-g2`: default debug level when using `-g`

      - `-g3`: includes extra debugging information (macro definitions)

    - See
      #link(
        "https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html",
      )[GCC documentation]
      about debugging for more information

  ],
  [

    #align(center, [#image("dwarf_logo.jpg", height: 40%)])

  ],
)

=== Debugging with compiler optimizations

- Compiler optimizations (`-O<level>`) can lead to optimizing out some
  variables and function calls.

- Trying to display them with GDB will display

  - `$1 = <value optimized out>`

- If one wants to inspect variables and functions, it is possible to
  compile the code using `-O0` (no optimization).

  - _Note: The kernel can only be compiled with `-O2` or `-Os`_

- It is also possible to annotate function with compiler attributes:

  - `__attribute__((optimize("O0")))`

- Remove function `static` qualifier to avoid inlining the function

  - _Note: LTO (Link Time Optimization) can defeat this._

- Set a specific variable as `volatile` to prevent the compiler from
  optimizing it out.

== Instrumenting code crashes
<instrumenting-code-crashes>

=== Instrumenting code crashes

- Call stacks can be manually requested/generated in applications

- This can be done either with specialized libraries (eg:
  #link("https://www.nongnu.org/libunwind/man/libunwind(3).html")[libunwind])
  or even directly the C library, e.g by using `backtrace()`
  (#manpage("backtrace", "3")) with glibc:
#v(0.5em)
#[
  #show raw.where(lang: "c", block: true): set text(size: 16pt)
  ```c
    char **backtrace_symbols(void *const *buffer, int size);
  ```

  - We can wire those custom backtraces on signals thanks to `sigaction()`
    (#manpage("sigaction", "2"))

    - `SIGSEGV` signal can be hooked to dump a call stack of an invalid
      memory access
  #v(0.5em)
  ```c
    int sigaction(int sig, const struct sigaction *restrict act,
                  struct sigaction *restrict oact);
  ```
]

- Some libraries like
  #link("https://www.gnu.org/software/libsigsegv/")[libsigsegv] ease the
  instrumentation of those signals

=== Custom code crash report (1/2)

#table(
  columns: (50%, 50%),
  stroke: none,
  [

    ```c
    [...]
    void callee(void *ptr) {
      int *myptr = (int *)ptr;
      printf("Executing suspicious operationn");
      myptr[2] = 0;
    }

    void caller(void) {
      void *ptr = NULL;
      callee(ptr);
    }

    void segfault_handler(int sig) {
      void *array[20];
      size_t size;
      char msg[]= "Segmentation fault!n";

      write(STDERR_FILENO, msg, sizeof(msg));
      size = backtrace(array, 20);
      backtrace_symbols_fd(array, size, STDERR_FILENO);
      exit(1);
    }
    ```

  ],
  [

    #[ #set text(size: 13pt)
      ```C
      int main() {
        const struct sigaction act = {
          .sa_handler = segfault_handler,
          .sa_mask = 0,
          .sa_flags = 0,
        };
        if (sigaction(SIGSEGV, &act, NULL))
          exit(EXIT_FAILURE);
        printf("Calling a faulty function");
        caller();
        return 0;
      }
      ```
    ]

  ],
)

=== Custom code crash report (2/2)

```console
[root@arch-bootlin-alexis custom_backtrace]# ./main
Calling a faulty function
Executing suspicious operation
Segmentation fault!
./main(segfault_handler+0x60)[0x55c6e4c1723c]
/usr/lib/libc.so.6(+0x38f50)[0x7fecb0a95f50]
./main(callee+0x2b)[0x55c6e4c171b4]
./main(caller+0x1c)[0x55c6e4c171d9]
./main(main+0x2c)[0x55c6e4c1729a]
/usr/lib/libc.so.6(+0x23790)[0x7fecb0a80790]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7fecb0a8084a]
./main(_start+0x25)[0x55c6e4c170b5]
```

- Writing robust signal handlers is not easy

  - When your application has received a `SIGSEGV` signal, its execution
    can not really be trusted anymore

  - We are for example supposed to use only
    #link(
      "https://man7.org/linux/man-pages/man7/signal-safety.7.html",
    )[reentrant functions]
    in signal handlers

  - Not following this rule may lead to undefined behavior

== The ptrace system call
<the-ptrace-system-call>

=== ptrace

- The _ptrace_ mechanism allows processes to trace other processes
  by accessing tracee memory and register contents

- A tracer can observe and control the execution state of another
  process

- Works by attaching to a tracee process using the `ptrace()` system
  call (see #manpage("ptrace", "2"))

- Can be executed directly using the `ptrace()` call but often used
  indirectly using other tools.
#[ #set text(size: 19pt)
  ```C
  long ptrace(enum __ptrace_request request, pid_t pid, void *addr, void *data);
  ```
]
- Used by _GDB_, _strace_ and all debugging tools that need
  access to the tracee process state

== GDB
<gdb>

#include "/common/gdb.typ"

=== GDB: going further

- Tutorial: Debugging Embedded Devices using GDB - Chris Simmonds, 2020

  - Slides:
    #text(size: 18pt)[#link(
      "https://elinux.org/images/0/01/Debugging-with-gdb-csimmonds-elce-2020.pdf",
    )]

  - Video:
    #link(
      "https://www.youtube.com/watch?v=JGhAgd2a_Ck",
    )[https://www.youtube.com/watch?v=JGhAgd2a_Ck]

#v(0.5em)

#align(center, [#image("gdb_tuto_elce_2020.png", height: 70%)])

=== GDB Python Extension

- GDB features a
  #link("https://sourceware.org/gdb/onlinedocs/gdb/Python.html")[python integration],
  allowing to script some debugging operations

- When executing python under GDB, a module named _gdb_ is
  available and all the GDB specific classes are accessible under this
  module

- Allows to add new types of commands, breakpoint, printers

  - Used by the kernel to create new commands with the python GDB
    scripts

- Allows full control and observability over the debugged program using
  GDB capabilities from Python scripts

  - Controlling execution, adding breakpoints, watchpoints, etc

  - Accessing the process memory, frames, symbols, etc

#v(0.5em)

#align(center, [#image("python_logo.pdf", height: 20%)])

=== GDB Python Extension (1/2)

```python
class PrintOpenFD(gdb.FinishBreakpoint):
  def __init__(self, file):
    self.file = file
    super(PrintOpenFD, self).__init__()

  def stop (self):
    print ("---> File " + self.file + " opened with fd " + str(self.return_value))
    return False

class PrintOpen(gdb.Breakpoint):
  def stop(self):
    PrintOpenFD(gdb.parse_and_eval("file").string())
    return False

class TraceFDs (gdb.Command):
  def __init__(self):
    super(TraceFDs, self).__init__("tracefds", gdb.COMMAND_USER)

  def invoke(self, arg, from_tty):
    print("Hooking open() with custom breakpoint")
    PrintOpen("open")

TraceFDs()
```

=== GDB Python Extension (2/2)

- Python scripts can be loaded using gdb `source` command

  - Or the script can be named <program>-gdb.py and will be loaded
    automatically by GDB

#v(0.5em)

```console
(gdb) source trace_fds.py
(gdb) tracefds
Hooking open() with custom breakpoint
Breakpoint 1 at 0x33e0
(gdb) run
Starting program: /usr/bin/touch foo bar
Temporary breakpoint 2 at 0x5555555587da
---> File foo opened with fd 3
Temporary breakpoint 3 at 0x5555555587da
---> File bar opened with fd 0
```

=== Common debugging issues

- You will likely encounter some issues while debugging, like poor
  address->symbols conversion, "optimized out" values or functions,
  empty backtraces...

- A quick checklist before starting debugging can spare you some
  troubles:

  - Make sure your host binary has
    #link("https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html")[debug symbols]:
    with gcc, ensure `-g` is provided, and use non-stripped version with
    host gdb

  - Disable
    #link(
      "https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Optimize-Options.html",
    )[optimizations]
    on final binary (`-O0`) if possible, or at least use a less
    intrusive level (`-Og`)

    - Static functions can for example be folded into caller depending
      on the optimization level, so they would be missing from
      backtraces

  - Prevent code optimization from reusing frame pointer register: with
    GCC, make sure `-fno-omit-frame-pointer` option is set

    - Not only true for debugging: any profiling/tracing tool relying on
      backtraces will benefit from it

- Your application is probably composed of multiple libraries: you will
  need to apply those configurations on all used components!

#setuplabframe([Solving an application crash], [

  Debugging an application crash

  - Code generation analysis with compiler-explorer

  - Using GDB and its Python support

  - Analyzing and using a coredump

])
