#!/bin/sh

nb_files=$(git ls-files | wc -l)
printf "close to %.0fk files, " $(echo "scale=5; $nb_files / 1000" | bc)

# Ignoring stdout because of symlinks to directories and spaces in filepaths.
git ls-files | xargs cat 2>/dev/null | wc | \
	awk '{printf "%.0fM lines, %.1fGiB\n", $1/1e6, $3/1024^3}'

echo

dirs="$(find * -maxdepth 0 -type d)"
total=$(printf "%s\n" $dirs | xargs -I{} find {} -type f -print0 | xargs -0 cat | wc -l)

for dir in $dirs
do
	lines=$(find $dir -type f -print0 | xargs -0 cat | wc -l)
	percent=$(echo "scale=5; $lines / $total * 100" | bc)
	if test $(echo "$percent >= 10" | bc) -eq 1
	then
		printf "\\item \\kdir{%s}: %.0f\\%%\n" $dir $percent
	else
		printf "\\item \\kdir{%s}: %.1f\\%%\n" $dir $percent
	fi
done | sort -nrk3

echo
echo "files at root:"
find * -maxdepth 0 -type f | awk 'NR==1{printf "%s", $0} NR!=1{printf ", %s", $0} END{printf "\n"}'
