#! /bin/sh
# Enforces correct geometry settings for OMAP rom monitor
DRIVE=$1
SIZE=`fdisk -l $DRIVE | grep Disk | grep bytes | awk '{print $5}'`
CYLINDERS=`echo $SIZE/255/63/512 | bc`
sfdisk -D -H 255 -S 63 -C $CYLINDERS $DRIVE << EOF
;
EOF
