#!/bin/sh
# Reboots the system
echo "Content-type: text/html"
echo
echo "<html><header></header><body>"
echo "<h1>Rebooting the system</h1>"
echo "<font color=Blue>"
echo "System reboot initiated" 
echo "</font>"
echo "</body></html>"
reboot
